# Generated by Django 4.1.7 on 2023-02-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliendId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliend_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Client ID',
            },
        ),
        migrations.CreateModel(
            name='ClientSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_secret', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Client Secret',
            },
        ),
    ]
