# Generated by Django 4.1.7 on 2023-02-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliendid_clientsecret'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CliendId',
            new_name='ClientId',
        ),
    ]
