# Generated by Django 4.1.7 on 2023-02-17 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_spotifyuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientid',
            old_name='cliend_id',
            new_name='client_id',
        ),
    ]
